---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/authors/{id}":
    get:
      summary: Retrieves an author
      tags:
      - Author
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: author found
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  bio:
                    type: string
                  photo:
                    type: string
                required:
                - id
                - name
            application/xml:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
                  bio:
                    type: string
                  photo:
                    type: string
                required:
                - id
                - name
        '404':
          description: blog not found
        '406':
          description: unsupported accept header
servers:
- url: https://{defaultHost}
  variables:
    defaultHost:
      default: www.example.com
